# Generated by Django 6.0.3 on 2026-03-06 09:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProductImage',
        ),
    ]
